FROM ubuntu:latest

# Install dependencies
RUN apt-get update && apt-get install -y wget curl gnupg software-properties-common apt-transport-https && rm -rf /var/lib/apt/lists/*

# Install Java
RUN mkdir -p /etc/apt/keyrings \
    && wget -O /etc/apt/keyrings/adoptium.asc https://packages.adoptium.net/artifactory/api/gpg/key/public \
    && echo "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list \
    && apt-get update && apt-get install -y temurin-17-jdk

# Install Jenkins
RUN curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | gpg --dearmor --output /usr/share/keyrings/jenkins-keyring.gpg \
    && echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian-stable binary/ | tee /etc/apt/sources.list.d/jenkins.list \
    && apt-get update && apt-get install -y jenkins

# Configure Jenkins to run directly
ENTRYPOINT ["java", "-jar", "/usr/share/jenkins/jenkins.war"]
CMD ["--httpPort=8080"]
