version: '3.8'

services:
  sonarqube:
    build:
      context: .  # Docker context set to the directory containing the Dockerfile_Sonar
      dockerfile: Dockerfile
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf

  # Other services as previously defined
  trivy:
    image: aquasec/trivy:latest
    container_name: trivy
    command: server --listen 0.0.0.0:4954
    ports:
      - "4954:4954"

  maven:
    image: maven:3.8.4-openjdk-17
    container_name: maven
    volumes:
      - ./project:/usr/src/mymaven
      - maven_repo:/root/.m2
    working_dir: /usr/src/mymaven
    command: tail -f /dev/null

  owasp:
    image: owasp/dependency-check:latest
    container_name: owasp
    volumes:
      - ./project:/src
      - dependency_data:/usr/share/dependency-check/data
    command: ["--project", "MyProject", "--scan", "/src", "--format", "ALL"]

volumes:
  maven_repo: {}
  dependency_data: {}
  sonarqube_conf: {}
