FROM ubuntu:latest

# Install dependencies
RUN apt-get update && apt-get install -y wget curl openjdk-11-jdk && rm -rf /var/lib/apt/lists/*

# Download Jenkins WAR
RUN wget http://updates.jenkins-ci.org/download/war/2.346.1/jenkins.war -O /opt/jenkins.war

# Set environment variables for Java
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH

# Expose port for Jenkins
EXPOSE 8080

# Set entry point to run Jenkins
ENTRYPOINT ["java", "-jar", "/opt/jenkins.war"]
CMD ["--httpPort=8080"]
