# Using OWASP Dependency Check official image
FROM owasp/dependency-check:latest

# Set the working directory
WORKDIR /src

# Volume to store results and data
VOLUME ["/src", "/usr/share/dependency-check/data"]

# Default command to run analysis
CMD ["--project", "MyProject", "--scan", "/src", "--format", "ALL", "--out", "/src/dependency-check-report.xml"]
